//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class BankAccountControl {
    
    /// <summary>
    /// rdoUseOldBank control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxRadioButtonList rdoUseOldBank;
    
    /// <summary>
    /// rpnOldBankAccount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel rpnOldBankAccount;
    
    /// <summary>
    /// ctrlBankAccount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::BankAccountComboControl ctrlBankAccount;
    
    /// <summary>
    /// rpnNewBankAccount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel rpnNewBankAccount;
    
    /// <summary>
    /// ASPxLabel4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel4;
    
    /// <summary>
    /// ctrlBankAccountCategory control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.Controls.CategoryControl ctrlBankAccountCategory;
    
    /// <summary>
    /// ASPxLabel2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel2;
    
    /// <summary>
    /// cbpAccountName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel cbpAccountName;
    
    /// <summary>
    /// PanelContent1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxPanel.PanelContent PanelContent1;
    
    /// <summary>
    /// ctrlMLSAccountName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.Controls.MLSControl ctrlMLSAccountName;
    
    /// <summary>
    /// btnRefreshAccountName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxImage btnRefreshAccountName;
    
    /// <summary>
    /// ASPxLabel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel1;
    
    /// <summary>
    /// ctrlOrganization control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.UserControls.OrganizationControl ctrlOrganization;
    
    /// <summary>
    /// LabelAccountNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel LabelAccountNumber;
    
    /// <summary>
    /// TextAccountNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.Controls.BankAccountNumberControl TextAccountNumber;
    
    /// <summary>
    /// LabelOpenDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel LabelOpenDate;
    
    /// <summary>
    /// DateOpenFrom control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.Controls.DateTimeControl DateOpenFrom;
    
    /// <summary>
    /// trDirectDebit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableRow trDirectDebit;
    
    /// <summary>
    /// ASPxLabel3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel3;
    
    /// <summary>
    /// ctrlTimeInterval control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::WebHelper.UserControls.TimeIntervalControl ctrlTimeInterval;
}
