//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBizPortal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBizPortal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResBizPortal", typeof(ResBizPortal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบงานนี้อนุญาตให้เข้าใช้ได้เฉพาะผู้ที่ได้รับอนุญาตเท่านั้น ผู้ใดพยายามเข้าใช้งานโดยไม่ได้รับอนุญาต หรือใช้งานเกินกว่าที่ได้รับอนุญาตจะถูกตรวจสอบและ บันทึกการใช้งานดังกล่าว อนึ่งการใช้งานอย่างไม่เหมาะสมของผู้ที่ได้รับอนุญาตก็อาจ ถูกตรวจสอบและบันทึกการใช้งานด้วยเช่นเดียวกัน ผู้เข้าใช้ระบบงานทุกคนถือว่า ตกลงและยินยอมให้ธนาคารสามารถดำเนินการดังกล่าวได้ รวมทั้งยินยอมให้อำนาจ ธนาคารดำเนินการการจัดส่งหลักฐานการตรวจสอบติดตามดังกล่าวเพื่อดำเนินการ ทางกฎหมายในกรณีที่ธนาคารพิจารณาเห็นว่าการเข้าใช้ระบบงานนี้อาจเป็นกา [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AccessPolicy {
            get {
                return ResourceManager.GetString("AccessPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอมรับ.
        /// </summary>
        public static string AgreeAccessPolicy {
            get {
                return ResourceManager.GetString("AgreeAccessPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ยอมรับ.
        /// </summary>
        public static string DisAgreeAccessPolicy {
            get {
                return ResourceManager.GetString("DisAgreeAccessPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดรายงานเป็น Excel.
        /// </summary>
        public static string DownloadReportAsExcelFile {
            get {
                return ResourceManager.GetString("DownloadReportAsExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดรายงานเป็น PDF .
        /// </summary>
        public static string DownloadReportAsPDFFile {
            get {
                return ResourceManager.GetString("DownloadReportAsPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่าน.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนของธนาคาร.
        /// </summary>
        public static string iBankAdminSide {
            get {
                return ResourceManager.GetString("iBankAdminSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string LOGON {
            get {
                return ResourceManager.GetString("LOGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการผู้ใช้งานระบบของ.
        /// </summary>
        public static string MemberUserManagement {
            get {
                return ResourceManager.GetString("MemberUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณมี {0} รายการรออยู่.
        /// </summary>
        public static string MultipleTransactionAwaitingConsideration {
            get {
                return ResourceManager.GetString("MultipleTransactionAwaitingConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่มีรายการรออยู่.
        /// </summary>
        public static string NoTransactionAwaitingConsideration {
            get {
                return ResourceManager.GetString("NoTransactionAwaitingConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณมี 1 รายการรออยู่.
        /// </summary>
        public static string OneTransactionAwaitingConsideration {
            get {
                return ResourceManager.GetString("OneTransactionAwaitingConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเมนู.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์รายงาน.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสผ่าน.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อเข้าใช้ระบบ.
        /// </summary>
        public static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการธนาคารทางอินเตอร์เน็ต.
        /// </summary>
        public static string ToInternetBanking {
            get {
                return ResourceManager.GetString("ToInternetBanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเข้าใช้ระบบ.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยินดีต้อนรับเข้าสู่บริการธนาคารทางอินเตอร์เน็ต.
        /// </summary>
        public static string WELCOMEtointernetbanking {
            get {
                return ResourceManager.GetString("WELCOMEtointernetbanking", resourceCulture);
            }
        }
    }
}
