//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResGeneral", typeof(ResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าใช้งาน.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบัญชี.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเล่นบัญชี.
        /// </summary>
        public static string AccountNickName {
            get {
                return ResourceManager.GetString("AccountNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัญชี.
        /// </summary>
        public static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทบัญชี.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งานได้.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่มีผล.
        /// </summary>
        public static string ActiveDate {
            get {
                return ResourceManager.GetString("ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลการกระทำ.
        /// </summary>
        public static string ActivityResult {
            get {
                return ResourceManager.GetString("ActivityResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มผู้ดูแลระบบ.
        /// </summary>
        public static string AddAdministrator {
            get {
                return ResourceManager.GetString("AddAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มผู้อนุมัติ.
        /// </summary>
        public static string AddApprover {
            get {
                return ResourceManager.GetString("AddApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มค่าธรรมเนียม.
        /// </summary>
        public static string AddFee {
            get {
                return ResourceManager.GetString("AddFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมไม่มีโซน.
        /// </summary>
        public static string AddGenaralFee {
            get {
                return ResourceManager.GetString("AddGenaralFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมมีโซน.
        /// </summary>
        public static string AddIRFee {
            get {
                return ResourceManager.GetString("AddIRFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มผู้ทำรายการ.
        /// </summary>
        public static string AddMaker {
            get {
                return ResourceManager.GetString("AddMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการโอนเงิน.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเพิ่มบริการชำระค่าสาธารณูปโภคและค่าธรรมเนียม.
        /// </summary>
        public static string AddServiceFee {
            get {
                return ResourceManager.GetString("AddServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มผู้ใช้งาน.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มโซน.
        /// </summary>
        public static string AddZone {
            get {
                return ResourceManager.GetString("AddZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * สถานะ PA=Pending Approval, WA=Waiting Amendment, R=Rejected, PA(m)=Pending more Approvals, A=Approved, C=Canceled, P=Processing, IF=Insufficient Fund, T=Terminated, DF=Debit Failed, DO=Debit Overridden, F=Failed, S=Success, PS=Partial Success, ST=Stoped.
        /// </summary>
        public static string AllTransactionStatus {
            get {
                return ResourceManager.GetString("AllTransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationID.
        /// </summary>
        public static string ApplicationID {
            get {
                return ResourceManager.GetString("ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติโดย.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่อนุมัติ.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อกลุ่มผู้อนุมัติ.
        /// </summary>
        public static string ApproveGroupName {
            get {
                return ResourceManager.GetString("ApproveGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้อนุมัติรายการ.
        /// </summary>
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สกุลเงิน.
        /// </summary>
        public static string BaseCurrency {
            get {
                return ResourceManager.GetString("BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาท.
        /// </summary>
        public static string Bath {
            get {
                return ResourceManager.GetString("Bath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการชำระค่าสาธารณูปโภค.
        /// </summary>
        public static string BillPaymentService {
            get {
                return ResourceManager.GetString("BillPaymentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการชำระค่าสาธารณูปโภค.
        /// </summary>
        public static string BillPaymentServiceManagement {
            get {
                return ResourceManager.GetString("BillPaymentServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนวณค่าธรรมเนียม.
        /// </summary>
        public static string Caculate {
            get {
                return ResourceManager.GetString("Caculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนวนสำเร็จ.
        /// </summary>
        public static string CaculateSuccess {
            get {
                return ResourceManager.GetString("CaculateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนวน.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลเช็ค.
        /// </summary>
        public static string ChequesInformation {
            get {
                return ResourceManager.GetString("ChequesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลข CIF.
        /// </summary>
        public static string CifNo {
            get {
                return ResourceManager.GetString("CifNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitizenIDPassportID.
        /// </summary>
        public static string CitizenIDPassportID {
            get {
                return ResourceManager.GetString("CitizenIDPassportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลียร์.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอก.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิด.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัส.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักประกัน.
        /// </summary>
        public static string Collateral {
            get {
                return ResourceManager.GetString("Collateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบริษัท.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลบริษัท.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริษัท.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการบันทึก.
        /// </summary>
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การติดต่อ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ติดต่อ.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลา(วันที่).
        /// </summary>
        public static string CouponDates {
            get {
                return ResourceManager.GetString("CouponDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัตราดอกเบี้ย.
        /// </summary>
        public static string CouponRate {
            get {
                return ResourceManager.GetString("CouponRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชนิด.
        /// </summary>
        public static string CouponType {
            get {
                return ResourceManager.GetString("CouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างโดย.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้าง.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างหุ้นใหม่.
        /// </summary>
        public static string CreateNewStock {
            get {
                return ResourceManager.GetString("CreateNewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับจำนำ.
        /// </summary>
        public static string Creditor {
            get {
                return ResourceManager.GetString("Creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน.
        /// </summary>
        public static string CreditorID {
            get {
                return ResourceManager.GetString("CreditorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้รับจำนำหลักทรัพย์บริษัท.
        /// </summary>
        public static string CreditorInstrument {
            get {
                return ResourceManager.GetString("CreditorInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้รับจำนำ.
        /// </summary>
        public static string CreditorName {
            get {
                return ResourceManager.GetString("CreditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สกุลเงิน.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหุ้นปัจจุบัน.
        /// </summary>
        public static string CurrentPar {
            get {
                return ResourceManager.GetString("CurrentPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut off time.
        /// </summary>
        public static string Cutofftime {
            get {
                return ResourceManager.GetString("Cutofftime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้แทนผู้ถือหุ้นกู้.
        /// </summary>
        public static string DebentureHolderRepresentatives {
            get {
                return ResourceManager.GetString("DebentureHolderRepresentatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูล.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนก.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำอธิบาย.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกสมาชิก.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระงับการใช้งาน.
        /// </summary>
        public static string DisableUser {
            get {
                return ResourceManager.GetString("DisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนก.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขค่าธรรมเนียม.
        /// </summary>
        public static string EditFee {
            get {
                return ResourceManager.GetString("EditFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขบริการและค่าธรรมเนียม.
        /// </summary>
        public static string EditService {
            get {
                return ResourceManager.GetString("EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่มีผล.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เริ่มมีผลตั้งแต่.
        /// </summary>
        public static string EffectiveFrom {
            get {
                return ResourceManager.GetString("EffectiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่มีผล.
        /// </summary>
        public static string EffectivePeriod {
            get {
                return ResourceManager.GetString("EffectivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิ้นสุดการมีผล.
        /// </summary>
        public static string EffectiveTo {
            get {
                return ResourceManager.GetString("EffectiveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกระงับการใช้งาน.
        /// </summary>
        public static string EnableUser {
            get {
                return ResourceManager.GetString("EnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกใช้งาน.
        /// </summary>
        public static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ยกเลิก.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกการใช้งาน.
        /// </summary>
        public static string ExpireUser {
            get {
                return ResourceManager.GetString("ExpireUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งออกข้อมูล.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดึงข้อมูลออกเป็น Excel ไฟล์.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดึงข้อมูลออกเป็น PDF ไฟล์.
        /// </summary>
        public static string ExportPDF {
            get {
                return ResourceManager.GetString("ExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาในการโอน.
        /// </summary>
        public static string Express {
            get {
                return ResourceManager.GetString("Express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรสาร.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียม.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่ปรึกษาทางการเงิน.
        /// </summary>
        public static string FinancialAdvisor {
            get {
                return ResourceManager.GetString("FinancialAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมต่อธุรกรรม.
        /// </summary>
        public static string FixedAmount {
            get {
                return ResourceManager.GetString("FixedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งแต่วันที่.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการโอนเงิน.
        /// </summary>
        public static string FundsTranFerService {
            get {
                return ResourceManager.GetString("FundsTranFerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการบริการโอนเงิน.
        /// </summary>
        public static string FundsTranFerServiceManageMent {
            get {
                return ResourceManager.GetString("FundsTranFerServiceManageMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมไม่มีโซน.
        /// </summary>
        public static string GenaralFee {
            get {
                return ResourceManager.GetString("GenaralFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงเวลาที่ไม่เข้าสู่ระบบนานเกินกำหนด.
        /// </summary>
        public static string HasBeenLoginTooLong {
            get {
                return ResourceManager.GetString("HasBeenLoginTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วยเหลือ.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าเริ่มต้น.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iBank.
        /// </summary>
        public static string iBank {
            get {
                return ResourceManager.GetString("iBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่บัตรประจำตัวประชาชน.
        /// </summary>
        public static string IdentificationNoAdmin {
            get {
                return ResourceManager.GetString("IdentificationNoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหุ้นเริ่มต้น.
        /// </summary>
        public static string InitialPar {
            get {
                return ResourceManager.GetString("InitialPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินเริ่มต้น.
        /// </summary>
        public static string InitialSize {
            get {
                return ResourceManager.GetString("InitialSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ได้รับผลประโยชน์.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงที่มีผล.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมต่างโซน.
        /// </summary>
        public static string IRFee {
            get {
                return ResourceManager.GetString("IRFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสหลักทรัพย์สากล.
        /// </summary>
        public static string ISIN {
            get {
                return ResourceManager.GetString("ISIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขาย.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัท.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนหุ้นที่ออกขาย.
        /// </summary>
        public static string IssueSize {
            get {
                return ResourceManager.GetString("IssueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลา(ปี).
        /// </summary>
        public static string IssueTerm {
            get {
                return ResourceManager.GetString("IssueTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เปลี่ยนรหัสผ่านล่าสุด.
        /// </summary>
        public static string LastChangePassword {
            get {
                return ResourceManager.GetString("LastChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพเดทล่าสุด.
        /// </summary>
        public static string LastedUpdate {
            get {
                return ResourceManager.GetString("LastedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟังก์ชั่นล่าสุดที่ใช้.
        /// </summary>
        public static string LastFunctionUsed {
            get {
                return ResourceManager.GetString("LastFunctionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ใช้ฟังก์ชั่นล่าสุด.
        /// </summary>
        public static string LastFunctionUsedDate {
            get {
                return ResourceManager.GetString("LastFunctionUsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastPwdGenerate.
        /// </summary>
        public static string LastPwdGenerate {
            get {
                return ResourceManager.GetString("LastPwdGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้จัดการการจัดจำหน่าย.
        /// </summary>
        public static string LeadUnderwriter {
            get {
                return ResourceManager.GetString("LeadUnderwriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังดำเนินการ ....
        /// </summary>
        public static string LoadingPanel1 {
            get {
                return ResourceManager.GetString("LoadingPanel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งาน.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าระบบ / ออกจากระบบ.
        /// </summary>
        public static string LoginOrLogout {
            get {
                return ResourceManager.GetString("LoginOrLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มากกว่า.
        /// </summary>
        public static string LowerBound {
            get {
                return ResourceManager.GetString("LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ส่งเอกสาร.
        /// </summary>
        public static string MailingAddress {
            get {
                return ResourceManager.GetString("MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ทำรายการ.
        /// </summary>
        public static string Maker {
            get {
                return ResourceManager.GetString("Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญลักษณ์หุ้น.
        /// </summary>
        public static string MarketCode {
            get {
                return ResourceManager.GetString("MarketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ครบกําหนด.
        /// </summary>
        public static string MaturityDate {
            get {
                return ResourceManager.GetString("MaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมขั้นสูงสุด.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนครั้งที่เข้าสู่ระบบไม่สำเร็จ.
        /// </summary>
        public static string MaxLoginFailed {
            get {
                return ResourceManager.GetString("MaxLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวม.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมขั้นต่ำ.
        /// </summary>
        public static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์มือถือ.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขโดย.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่แก้ไข.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีหน่วย.
        /// </summary>
        public static string MutualFundAccount {
            get {
                return ResourceManager.GetString("MutualFundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต่อไป.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวเลือก.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สั่งวันที่.
        /// </summary>
        public static string OrderedDate {
            get {
                return ResourceManager.GetString("OrderedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่อื่นๆ.
        /// </summary>
        public static string OtherAddress {
            get {
                return ResourceManager.GetString("OtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนหุ้นที่ขายได้.
        /// </summary>
        public static string OutstandingSize {
            get {
                return ResourceManager.GetString("OutstandingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความยาวรหัสผ่านผู้ใช้งานระบบ.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความถี่ในการจ่ายปันผล.
        /// </summary>
        public static string PaymentFrequency {
            get {
                return ResourceManager.GetString("PaymentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมแปรผัน (%).
        /// </summary>
        public static string PercentageRate {
            get {
                return ResourceManager.GetString("PercentageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้จำนำ.
        /// </summary>
        public static string Pledger {
            get {
                return ResourceManager.GetString("Pledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน.
        /// </summary>
        public static string PledgerID {
            get {
                return ResourceManager.GetString("PledgerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้จำนำ.
        /// </summary>
        public static string PledgerName {
            get {
                return ResourceManager.GetString("PledgerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนผู้ถือหลักทรัพย์.
        /// </summary>
        public static string PortfolioID {
            get {
                return ResourceManager.GetString("PortfolioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนหน้า.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PwdGenerate.
        /// </summary>
        public static string PwdGenerate {
            get {
                return ResourceManager.GetString("PwdGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบสอบถาม.
        /// </summary>
        public static string Questionaire {
            get {
                return ResourceManager.GetString("Questionaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ธนาคารปลายทาง.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำสั่งเลขที่.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขอ้างอิง 1.
        /// </summary>
        public static string Reference1 {
            get {
                return ResourceManager.GetString("Reference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขอ้างอิง 2.
        /// </summary>
        public static string Reference2 {
            get {
                return ResourceManager.GetString("Reference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขอ้างอิง 3.
        /// </summary>
        public static string Reference3 {
            get {
                return ResourceManager.GetString("Reference3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขอ้างอิง 4.
        /// </summary>
        public static string Reference4 {
            get {
                return ResourceManager.GetString("Reference4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จากโซน.
        /// </summary>
        public static string RegionFrom {
            get {
                return ResourceManager.GetString("RegionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถึงโซน.
        /// </summary>
        public static string RegionTo {
            get {
                return ResourceManager.GetString("RegionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่ตั้งจดทะเบียน.
        /// </summary>
        public static string RegisteredAddress {
            get {
                return ResourceManager.GetString("RegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ลงทะเบียน.
        /// </summary>
        public static string RegisteredDate {
            get {
                return ResourceManager.GetString("RegisteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นายทะเบียน.
        /// </summary>
        public static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียน.
        /// </summary>
        public static string RegistrationNo {
            get {
                return ResourceManager.GetString("RegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนผู้อนุมัติร่วม.
        /// </summary>
        public static string RequiredNumberOfDistinctApprovals {
            get {
                return ResourceManager.GetString("RequiredNumberOfDistinctApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบหลักทรัพย์เลขที่.
        /// </summary>
        public static string ReservationNo {
            get {
                return ResourceManager.GetString("ReservationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งแก้ไข.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลสำเร็จ.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือก.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มบัญชีในการทำธุรกรรม.
        /// </summary>
        public static string SelectTransactionAccount {
            get {
                return ResourceManager.GetString("SelectTransactionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ธนาคารต้นทาง.
        /// </summary>
        public static string SenderBank {
            get {
                return ResourceManager.GetString("SenderBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการ.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อย่อ.
        /// </summary>
        public static string ServiceCode {
            get {
                return ResourceManager.GetString("ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เริ่มใช้เมื่อ.
        /// </summary>
        public static string ServiceFrom {
            get {
                return ResourceManager.GetString("ServiceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โอนต่อวันสูงสุด.
        /// </summary>
        public static string ServiceMaxAmountPerDay {
            get {
                return ResourceManager.GetString("ServiceMaxAmountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โอนต่อรายการสูงสุด.
        /// </summary>
        public static string ServiceMaxAmountPerTran {
            get {
                return ResourceManager.GetString("ServiceMaxAmountPerTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริการ.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลิกใช้เมื่อ.
        /// </summary>
        public static string ServiceTo {
            get {
                return ResourceManager.GetString("ServiceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลาใช้งานระบบ.
        /// </summary>
        public static string SessionTimeout {
            get {
                return ResourceManager.GetString("SessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ถือหลักทรัพย์ของบริษัท.
        /// </summary>
        public static string Shareholders {
            get {
                return ResourceManager.GetString("Shareholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดง.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะบัญชี.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string StatusUser {
            get {
                return ResourceManager.GetString("StatusUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โครงสร้างค่าธรรมเนียม.
        /// </summary>
        public static string StructerFee {
            get {
                return ResourceManager.GetString("StructerFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปรายละเอียด.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปบริการและค่าธรรมเนียม.
        /// </summary>
        public static string SummaryService {
            get {
                return ResourceManager.GetString("SummaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เทอม.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถึงวันที่.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to งวดวันที่.
        /// </summary>
        public static string TradeDate {
            get {
                return ResourceManager.GetString("TradeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีธุรกรรม.
        /// </summary>
        public static string TransactionAccount {
            get {
                return ResourceManager.GetString("TransactionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        public static string txtDate {
            get {
                return ResourceManager.GetString("txtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกข้อมูล!.
        /// </summary>
        public static string txtWarningMassageSelect {
            get {
                return ResourceManager.GetString("txtWarningMassageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกวันที่!.
        /// </summary>
        public static string txtWarningMassageSelectDate {
            get {
                return ResourceManager.GetString("txtWarningMassageSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกกองทุน!.
        /// </summary>
        public static string txtWarningMassageSelectFund {
            get {
                return ResourceManager.GetString("txtWarningMassageSelectFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หุ้น/หน่วย.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หุ้นละ/หน่วยละ.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพเดท.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ปรับปรุง.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาปรับปรุง.
        /// </summary>
        public static string UpdatedTS {
            get {
                return ResourceManager.GetString("UpdatedTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพเดทสถานะเช็ค.
        /// </summary>
        public static string UpdateStatusCheques {
            get {
                return ResourceManager.GetString("UpdateStatusCheques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลด.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่เกิน.
        /// </summary>
        public static string UpperBound {
            get {
                return ResourceManager.GetString("UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานทั้งหมด.
        /// </summary>
        public static string UserAll {
            get {
                return ResourceManager.GetString("UserAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานที่ถูกระงับ.
        /// </summary>
        public static string UserDisable {
            get {
                return ResourceManager.GetString("UserDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานที่ยังใช้งานได้.
        /// </summary>
        public static string UserEnable {
            get {
                return ResourceManager.GetString("UserEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานที่ยกเลิกไปแล้ว.
        /// </summary>
        public static string UserExpire {
            get {
                return ResourceManager.GetString("UserExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานที่เข้าสู่ระบบไม่สำเร็จเกินจำนวนที่กำหนด.
        /// </summary>
        public static string UserFailedLoginAttemp {
            get {
                return ResourceManager.GetString("UserFailedLoginAttemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเข้าใช้ระบบ.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการผู้ใช้งาน.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้งานระบบ.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงผู้ใช้งานที่ไม่เข้าสู่ระบบเกินจำนวนวันที่กำหนด.
        /// </summary>
        public static string UserReinStated {
            get {
                return ResourceManager.GetString("UserReinStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบ.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยินดีต้อนรับ.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
