//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResImageURL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResImageURL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResImageURL", typeof(ResImageURL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/accept.png.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/accept_disable.png.
        /// </summary>
        public static string Accept_disable {
            get {
                return ResourceManager.GetString("Accept_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/add.png.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/accept.png.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/accept_disable.png.
        /// </summary>
        public static string Approve_disable {
            get {
                return ResourceManager.GetString("Approve_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/arrow_left.png.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/coins.png.
        /// </summary>
        public static string Caculate {
            get {
                return ResourceManager.GetString("Caculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/CIMB_Icon/Calendar_Red.png.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/cancel.png.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/clear.png.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/cross.png.
        /// </summary>
        public static string Cross {
            get {
                return ResourceManager.GetString("Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/cross_disable.png.
        /// </summary>
        public static string Cross_disable {
            get {
                return ResourceManager.GetString("Cross_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_csv.png.
        /// </summary>
        public static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/bin_closed.png.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/bin_closed_disable.png.
        /// </summary>
        public static string Delete_disable {
            get {
                return ResourceManager.GetString("Delete_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/application_view_list.png.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/application_view_list_disable.png.
        /// </summary>
        public static string Detail_disable {
            get {
                return ResourceManager.GetString("Detail_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_csv.png.
        /// </summary>
        public static string Doc_CSV {
            get {
                return ResourceManager.GetString("Doc_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_excel_table.png.
        /// </summary>
        public static string Doc_Excel {
            get {
                return ResourceManager.GetString("Doc_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_pdf.png.
        /// </summary>
        public static string Doc_PDF {
            get {
                return ResourceManager.GetString("Doc_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_text.png.
        /// </summary>
        public static string Doc_TextFile {
            get {
                return ResourceManager.GetString("Doc_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/page_white_put.png.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/page_white_edit.png.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/page_white_editDisable.png.
        /// </summary>
        public static string Edit_disable {
            get {
                return ResourceManager.GetString("Edit_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/cross_octagon.png.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Excel.png.
        /// </summary>
        public static string Excel_128x128 {
            get {
                return ResourceManager.GetString("Excel_128x128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/delete.png.
        /// </summary>
        public static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/application_put.png.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/find.png.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/grid_selection.png.
        /// </summary>
        public static string GridSelection {
            get {
                return ResourceManager.GetString("GridSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/help.png.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/clock.png.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/house.png.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/arrow_right.png.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/arrow_left.png.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/printer.png.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/blog.png.
        /// </summary>
        public static string QuestTionaire {
            get {
                return ResourceManager.GetString("QuestTionaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/arrow_refresh.png.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/deleteEnable.png.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/delete_disable.gif.
        /// </summary>
        public static string Reject_disable {
            get {
                return ResourceManager.GetString("Reject_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/undo_green.png.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/undo_green_disable.png.
        /// </summary>
        public static string Return_disable {
            get {
                return ResourceManager.GetString("Return_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/disk.png.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/application_view_list.png.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/doc_text.png.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Text.png.
        /// </summary>
        public static string Text_128x128 {
            get {
                return ResourceManager.GetString("Text_128x128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/page_white_get.png.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/find.png.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/led_icon/warning.png.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
