//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPropertyName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPropertyName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResPropertyName", typeof(ResPropertyName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่กองทุน.
        /// </summary>
        public static string Fund_Address {
            get {
                return ResourceManager.GetString("Fund_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Fund.
        /// </summary>
        public static string Fund_ChildrenFundRelations {
            get {
                return ResourceManager.GetString("Fund_ChildrenFundRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมกองทุน.
        /// </summary>
        public static string Fund_FundFeeSchedules {
            get {
                return ResourceManager.GetString("Fund_FundFeeSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความสัมพันธ์ระหว่างองค์กร.
        /// </summary>
        public static string Fund_FundRelatedOrgs {
            get {
                return ResourceManager.GetString("Fund_FundRelatedOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par Values.
        /// </summary>
        public static string Fund_ParValues {
            get {
                return ResourceManager.GetString("Fund_ParValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดปฎิทินกองทุน.
        /// </summary>
        public static string Fund_TransactionsCalendar {
            get {
                return ResourceManager.GetString("Fund_TransactionsCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Fund.
        /// </summary>
        public static string FundRelation_ChildFund {
            get {
                return ResourceManager.GetString("FundRelation_ChildFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Fund.
        /// </summary>
        public static string FundRelation_ParentFund {
            get {
                return ResourceManager.GetString("FundRelation_ParentFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีธนาคาร.
        /// </summary>
        public static string Party_AssociatedBankAccounts {
            get {
                return ResourceManager.GetString("Party_AssociatedBankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณสมบัติ.
        /// </summary>
        public static string Party_Attributes {
            get {
                return ResourceManager.GetString("Party_Attributes", resourceCulture);
            }
        }
    }
}
